add Settings Page desktop et mobile
An-gova/angova-front pull request #12
Opened 2024-05-28 13:41 UTC by poppin94

- Ajout de la page Settings pour dektop et mobile
- update ui components button, max screen, navigation
- Ajout de components scroll area, switch button
- update docker-compose port app 3000

2024-05-28 13:43 UTC, Kv1k commented
Tu as des conflits à gerer

2024-05-29 15:13 UTC, MathisZerbib reviewed
bon travail, regardes mes commentaires

2024-05-29 15:13 UTC, MathisZerbib commented on app/user/settings/Settings.tsx
> +    // langue audio par default ?
Il manque une implémentation ?

2024-05-29 15:13 UTC, MathisZerbib commented on app/user/settings/Settings.tsx
> +    (_, i, a) => `v1.2.0-beta.${a.length - i}`
v1.2.0-beta devrais passer par une constante ou un variable d'environnement

2024-05-29 15:13 UTC, MathisZerbib commented on app/user/settings/Settings.tsx
> +            <div className='test'>
la className devrait avoir un autre nom plutôt que test s'il te plait

2024-05-29 15:13 UTC, MathisZerbib commented on components/BottomNavigation/index.tsx
> +            style={{ width: "auto", height: "auto" }} // to fix aspect ratio, this needs to be style to remove warning
on doit remove ça d'après le commentaire ?

2024-05-29 15:13 UTC, MathisZerbib commented on components/ui/button.tsx
> +        // orange: "bg-orange-400 text-white hover:bg-orange-500 rounded-sm",
to remove ?

2024-05-30 12:09 UTC, poppin94 commented on app/user/settings/Settings.tsx
> +    // langue audio par default ?
Alors ici je savais pas top si il c'etait clickable et si il y'avait une logique deriere. J'ai supprimmé l'implementation.

2024-05-30 12:09 UTC, poppin94 commented on app/user/settings/Settings.tsx
> +    (_, i, a) => `v1.2.0-beta.${a.length - i}`
Je l'utilisais pas je l'ai supprimé

2024-05-30 13:03 UTC, LDB47 requested changes

2024-05-30 13:03 UTC, LDB47 commented on app/user/settings/Settings.tsx
> +  const handleDefaultAudioClick = () => {
En fait il faut implémenter la fonctionnalité de choix de la langue audio stp

2024-05-30 13:32 UTC, poppin94 commented on app/user/settings/Settings.tsx
> +  const handleDefaultAudioClick = () => {
@LDB47  Cette fonction c'etait lors du clique sur "Langue audio par default". Je peux l'implementer mais juste ca correspond a quoi lorsqu'on clique sur "Langue audio par default" ? On peut choisir une langue écrit différente de celle de l'audio ?

![Screenshot from 2024-05-30 15-28-31](https://github.com/An-gova/angova-front/assets/62555098/0e3046da-b48f-45c1-aacb-7dff46843224)

2024-05-30 14:53 UTC, poppin94 commented on app/user/settings/Settings.tsx
> +  const handleDefaultAudioClick = () => {
Alors j'ai rajouté la logique au changement de langue je peux cliquer sur "Langue par default" et ca me Défini ma langue audio par default. J'ai rajouté un toast en haut a droite.
![Screenshot from 2024-05-30 16-51-56](https://github.com/An-gova/angova-front/assets/62555098/55bb3ee7-5695-4961-b23a-45a12ead047e)

2024-05-31 08:15 UTC, LDB47 commented on app/user/settings/Settings.tsx
> +  const handleDefaultAudioClick = () => {
![image](https://github.com/An-gova/angova-front/assets/92379383/b0d9738b-95a6-4cc8-9b84-af03cbdd006b)

Bien joué et on verra pour le choix différent dans un second temps, et la gestion de ça ;)

2024-05-31 08:29 UTC, LDB47 commented
Il faut resolve les conflits sur BottomNavigation please

2024-05-31 09:12 UTC, LDB47 reviewed
Conflits à gérer please

2024-05-31 09:20 UTC, poppin94 commented
> Conflits à gérer please

Il y'a des petits soucis sur la navigation mobile je regle ca

2024-05-31 09:27 UTC, poppin94 commented
> > Conflits à gérer please
> 
> Il y'a des petits soucis sur la navigation mobile je regle ca

2024-05-31 09:29 UTC, poppin94 commented
@LDB47 J'ai close sans faire expres... 
J'ai resolve les conflict normalement c'est Ok si tu peux check

2024-05-31 09:29 UTC, MathisZerbib approved these changes

2024-05-31 09:30 UTC, LDB47 approved these changes
Approved

2024-05-31 09:31 UTC, merged