Feature/dashboard profil
An-gova/angova-front pull request #20
Opened 2024-06-06 15:02 UTC by poppin94

Ajout de la page dashboard profil

Card classement général, Card Objectif et Niveau 

Integration Chart non dynamique

2024-06-06 16:42 UTC, MathisZerbib commented
resolve le petit conflit et on vois si on merge ce soir si t'es deter

2024-06-06 20:06 UTC, poppin94 commented
> resolve le petit conflit et on vois si on merge ce soir si t'es deter

@MathisZerbib J'ai fix le conflict mais du coup avec la navigation bottom la vue a été changé. De base ça donnait ça.

![Screenshot from 2024-06-06 17-11-29](https://github.com/An-gova/angova-front/assets/62555098/32c0da37-16f9-478b-8fca-9eade97aa844)

2024-06-06 22:15 UTC, MathisZerbib commented
Super ça ! Et bien on va pouvoir l'intégrer normalement ?

2024-06-06 22:40 UTC, poppin94 commented
> Super ça ! Et bien on va pouvoir l'intégrer normalement ?

Je termine quelque ajustement pour que ce soit mieux integré avec la navigation bottom et c'est good

2024-06-06 23:21 UTC, poppin94 commented
@MathisZerbib J'ai adapter la page avec la navigation bottom, et j'ai rajouter la modal "modifier les objectif"
![image](https://github.com/An-gova/angova-front/assets/62555098/43ca1a21-c68a-4180-9553-78cd899ef047)

C'est bon de mon coté donc si t'es ok tu peux merge.

2024-06-07 00:09 UTC, MathisZerbib commented
Parfait je regarde ça

2024-06-07 00:13 UTC, MathisZerbib requested changes

2024-06-07 00:13 UTC, MathisZerbib commented on components/ProgressChart.tsx
> +                text: 'Progression 2023',
2023 ?

2024-06-07 00:13 UTC, MathisZerbib commented on package.json
> -    "@types/react": "18.2.45",
Ça va pas break quelque chose ça ? Pourquoi avoir downgrade la version ?

2024-06-07 00:14 UTC, MathisZerbib commented
Bon travail en vrai ça rend bien ce dashboard, j'ai pas.du tout testé le.responsive cependant

2024-06-07 08:18 UTC, poppin94 commented on components/ProgressChart.tsx
> +                text: 'Progression 2023',
J'ai changé en 2024

2024-06-07 08:19 UTC, poppin94 commented on package.json
> -    "@types/react": "18.2.45",
Il me semble que c'est quand j'ai intégré la librairie chart js mais je pense pas que ca change quelque chose.

2024-06-07 09:24 UTC, MathisZerbib approved these changes

2024-06-07 09:26 UTC, MathisZerbib commented
Il manque le lien sur la flèche de retour qui ne fait rien

2024-06-07 09:44 UTC, poppin94 commented
> Il manque le lien sur la flèche de retour qui ne fait rien

Ca fonctionne bien le retour pour moi

2024-06-11 10:36 UTC, MathisZerbib commented
J'ai resolve le conflit du package.json tu pourras tester que ça marche bien ?  (remove node_modules + reinstall dependencies )

2024-06-11 10:46 UTC, merged

2024-06-11 12:24 UTC, poppin94 commented
> J'ai resolve le conflit du package.json tu pourras tester que ça marche bien ? (remove node_modules + reinstall dependencies ) Thxx

C'est Ok j'ai testé ca fonctionne.